name: Hello World

on:
    push:
        branches:
            - main  
    pull_request:
        branches:
            - main  
    workflow_dispatch:

  
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4 
            - name: Hello World
              run: ech "Hello World"
              shell: bash
    
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Goodbye world
              run: ech "Goodbye World"
              shell: bash
